### ISSUE TITLE
Add the project tech stack to the readme

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/college-notification-app#1]
# Feature Request

### Describe your problem
Add the project tech stack to the readme.

**Comment by Tlazypanda** [comment]
Assigned to @Pranshu-Tripathi

**Comment by Pranshu-Tripathi** [comment]
Add https://github.com/Pranshu-Tripathi as a contributor for code.

**Comment by Pranshu-Tripathi** [comment]
@all-contributors please add Pranshu-Tripathi for Code
