### ISSUE TITLE
Set up the widgets and design for activity_login.xml.

### ISSUE THREAD

**Issue by siddhantdrk** [Elevate-Lab/college-notification-app#10]
# Feature Request

### Describe your problem

Set up the respective containers and widgets positions as per the attached screenshot in activity_login.xml. .
Don't need to set up the background themes and image assets.
Ignore the dots in the text input fields.

### Note
Make sure you have the latest version (4.1+) of Android Studio or else update it.
Use Margin values for layouts and widgets as
8dp, 16dp,24dp, 32dp, 
with context to observation in attached screenshot.

### Describe the solution you'd like

![login_activity](https://user-images.githubusercontent.com/58393179/96301242-86aff180-1014-11eb-9cf7-79aad8afd929.jpeg)

### Quick resources to refer
https://www.udemy.com/course/learn-android-application-development-y/learn/lecture/7810222#overview

**Comment by Cybertron-Avneesh** [comment]
I want to work on this issue.

**Comment by tejma17** [comment]
@Cybertron-Avneesh, you can work on this issue.

**Comment by Devildarkfire** [comment]
can i work on this

**Comment by siddhantdrk** [comment]
@Devildarkfire go ahead🚀
