### ISSUE TITLE
Set up the widgets and design for activity_sing_up.xml.

### ISSUE THREAD

**Issue by siddhantdrk** [Elevate-Lab/college-notification-app#11]
# Feature Request

### Describe your problem

Set up the respective containers and widgets positions as per the attached screenshot in activity_sign_up.xml. .
Don't need to set up the background themes and image assets.
Ignore the dots in the text input fields.

### Note
Make sure you have the latest version (4.1+) of Android Studio or else update it.
Use Margin values for layouts and widgets as
8dp, 16dp,24dp, 32dp, 
with context to observation in attached screenshot.

### Describe the solution you'd like

![signup_activity](https://user-images.githubusercontent.com/58393179/96301712-308f7e00-1015-11eb-8bec-72f67a3b3aca.jpeg)

### Quick resources to refer
https://www.udemy.com/course/learn-android-application-development-y/learn/lecture/7810222#overview

**Comment by Jyotika999** [comment]
Can I work on this ?

**Comment by tejma17** [comment]
Hi @Jyotika999, you are assigned
