### ISSUE TITLE
Setting up a splash screen in the beginning of the launch of the app

### ISSUE THREAD

**Issue by Jyotika999** [Elevate-Lab/college-notification-app#18]
# Feature Request

###  problem

I have tried my hands on making the splash screen of the application, ON TIME PRO with an image which could be replaced later too.

### solution 

Hence, for the above mentioned scenario , I am working on the splash screen for the app with animation

**Comment by Jyotika999** [comment]
Can I work further on this and submit a PR?

**Comment by siddhantdrk** [comment]
@Jyotika999  go ahead🚀
