### ISSUE TITLE
Change the App Theme in styles.xml to Theme.MaterialComponents.DayNight.NoActionBar.Bridge

### ISSUE THREAD

**Issue by siddhantdrk** [Elevate-Lab/college-notification-app#19]
# Feature Request

### Describe your problem

Currently the Application theme is Theme.AppCompat.Light.NoActionBar. Need to change it to Theme.MaterialComponents.DayNight.NoActionBar.Bridge

### Describe the solution you'd like

Change the App Theme to Theme.MaterialComponents.DayNight.NoActionBar.Bridge

**Comment by Devildarkfire** [comment]
I want to work on this

**Comment by siddhantdrk** [comment]
@Devildarkfire  go ahead
