### ISSUE TITLE
Add Intent From Welcome Activity to Login Activity

### ISSUE THREAD

**Issue by Pranshu-Tripathi** [Elevate-Lab/college-notification-app#24]
# Make Intent to Login Activity From Welcome Activity

### Description Of Task : 

 Welcome Activity is already been made with completion of xml file. Now the app needs to switch to Login activity.

### Prior Knowledge and Resources: 
You should know following concepts : 
- intents in java

Resource can be found here : https://developer.android.com/reference/android/content/Intent

### Note : 

- Expected Changes only in WelcomeActivity.java .Make sure While making the PRS other files are not changed
- Intent should clear tops on leaving the screen so that the onBackPressed the app should close and not take back to welcomeActivity.java

**Comment by Cybertron-Avneesh** [comment]
Can I go ahead with this issue?

**Comment by Pranshu-Tripathi** [comment]
Sure @Cybertron-Avneesh
