### ISSUE TITLE
Add Intent From WelcomeActivity.java to RegisterActivity.java

### ISSUE THREAD

**Issue by Pranshu-Tripathi** [Elevate-Lab/college-notification-app#25]
# Make Intent from WelcomeActivity.java to RegisterActivity.java

### Description : 

Using intents make intent from welcome activity to register activity.

### Prior Knowledge & Resources: 

Required Knowledge on : 

- Intents

Resources : https://developer.android.com/reference/android/content/Intent

### Note:

- Expected Changes only in Welcome Activity.java . While Making PR make sure that no other files are changed.

- Clear the tops of the screen while making intents. So onBackPressed the app should not return to welcome screen rather should shutdown the app

**Comment by cyber-venom003** [comment]
@Pranshu-Tripathi please assign it to me, I want to work on this.

**Comment by Pranshu-Tripathi** [comment]
Sure @cyber-venom003 !

**Comment by sobhanbera** [comment]
Can I work on this @Pranshu-Tripathi or this has been done.

**Comment by Pranshu-Tripathi** [comment]
@SobhanBera sorry for now. This issue is already assigned to @cyber-venom003 . Will surely find some issues for you in the future :)

**Comment by sobhanbera** [comment]
That's Fine
