### ISSUE TITLE
Add Intent from LoginActivity to SignUpAvtivity On Clicking the Sign Up TextView at the bottom.

### ISSUE THREAD

**Issue by siddhantdrk** [Elevate-Lab/college-notification-app#36]
# Feature Request

Clicking on the SignUp textview at the bottom must open the SignUpActivity.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/58393179/97775176-a9014d80-1b84-11eb-94fc-6461e50fb08a.png)

**Comment by Devildarkfire** [comment]
Can I work on this

**Comment by siddhantdrk** [comment]
@Devildarkfire  go ahead

**Comment by darsh8114** [comment]
Can I work on it? i

**Comment by siddhantdrk** [comment]
@darsh8114  Sorry the issue is assigned @Devildarkfire  just keep yourself updated about the repo more issues will be up soon.
