### ISSUE TITLE
Add Intent from SignUpActivity to LoginAvtivity On Clicking the Sign In TextView at the bottom.

### ISSUE THREAD

**Issue by siddhantdrk** [Elevate-Lab/college-notification-app#37]
# Feature Request

### Describe your problem
Clicking on the SignIn textview at the bottom must open the LoginActivity.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/58393179/97775226-1319f280-1b85-11eb-8d08-43961600129f.png)

**Comment by Jyotika999** [comment]
Can I work on this?

**Comment by siddhantdrk** [comment]
@Jyotika999  go ahead

**Comment by kajal1811** [comment]
Can I work on this?

**Comment by siddhantdrk** [comment]
@kajal1811 welcome to ElevateLab 😊 Sorry the issue is already assigned to @Jyotika999. Anyways stay updated about the repo more issues will be coming soon over it.

**Comment by kajal1811** [comment]
Okay, sure.

**Comment by siddhantdrk** [comment]
@kajal1811  you can go ahead with it

**Comment by darsh8114** [comment]
Can I work on it? I think It is not assigned to anyone.

**Comment by siddhantdrk** [comment]
@darsh8114  go ahead🚀
