### ISSUE TITLE
Define the methods initViews() in all Activities in which doing findViewById for all xml views/objects.

### ISSUE THREAD

**Issue by siddhantdrk** [Elevate-Lab/college-notification-app#45]
# Feature Request

### Describe your problem
- Defining separate method for intializing views is always a good practice.
- You need to define a separate method named initViews() in each  activity below with respective to the widgets used in  xmls.
   - WelcomeActivity
   - LoginActivity
   - SignUpActivity
- Please don't change the already declared variable names for buttons/views just keep them same and intialize/findViewById in initViews() method. 
- After Defining call the method in OnCreate

**Comment by Cybertron-Avneesh** [comment]
I would like to work on this issue.

**Comment by siddhantdrk** [comment]
@Cybertron-Avneesh  go ahead
