### ISSUE TITLE
Set up the widgets and design for activity_welcome.xml.

### ISSUE THREAD

**Issue by siddhantdrk** [Elevate-Lab/college-notification-app#9]
# Feature Request

### Describe your problem

 Set up the respective containers and widgets positions as per the attached screenshot in activity_welcome.xml. . 
 Don't need to set up the background themes.

### Note
Make sure you have the latest version (4.1+) of Android Studio or else update it.
Use Margin values for layouts and widgets as
8dp, 16dp,24dp, 32dp, 
with context to observation in attached screenshot.
### Describe the solution you'd like

![welcome_activity](https://user-images.githubusercontent.com/58393179/96300587-659ad100-1013-11eb-968a-500a710a9691.jpeg)

### Quick resources to refer
https://www.udemy.com/course/learn-android-application-development-y/learn/lecture/7810222#overview

**Comment by IC1101Virgo** [comment]
Can I work on this?

**Comment by tejma17** [comment]
@IC1101Virgo go ahead

**Comment by siddhantdrk** [comment]
@IC1101Virgo  what's the status??

**Comment by IC1101Virgo** [comment]
@siddhantdrk Will make the PR by tonight. :)

**Comment by Mandar16** [comment]
can I work on this

**Comment by siddhantdrk** [comment]
@Mandar16  go head🚀
